# İlgili Go tabanlı Docker görüntüsünü seçin
FROM golang:1.20

# Çalışma dizinini ayarlayın
WORKDIR /app

# Gerekli dosyaları kopyalayın
COPY . .

# Gerekli paketleri yükleyin
RUN go mod download

# Uygulamayı derleyin
RUN go build -o main .

EXPOSE 3000

# Uygulamayı çalıştırın
CMD ["./main"]